Lab5/Lab5/Models/Account.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.Models
{
    public class Account
    {
    }
}

Lab5/Lab5/Models/ErrorViewModel.cs
using System;

namespace Lab5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab5/Lab5/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

Lab5/Lab5/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab5.Models
{
    public class RegisterViewModel
    {
        [Required] 
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required] 
        public string FullName { get; set; }
        [Required] 
        public string PhoneNumber { get; set; }
        [Required] 
        public string Email { get; set; }
        [Required]
        [Compare("Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public string ReturnUrl { get; set; }
    }
}

Lab5/Lab5/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IdentityServer4.Services;
using Lab5.Models;
using Microsoft.AspNetCore.Identity;

namespace Lab5.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IIdentityServerInteractionService _interactionService;

        public AuthController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IIdentityServerInteractionService interactionService)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _interactionService = interactionService;
        }
        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
           var viewModel = new LoginViewModel
           {
               ReturnUrl = returnUrl
           };
           return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var user = await _userManager.FindByNameAsync(viewModel.UserName);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User not found");
                return View(viewModel);
            }

            var result = await _signInManager.PasswordSignInAsync(viewModel.UserName, viewModel.Password, false, false);
            if (result.Succeeded)
            {
                var claims = new List<Claim>
                {
                    new Claim("fullname", user?.FullName)
                };
                await _signInManager.SignInWithClaimsAsync(user, false, claims);
                return Redirect("/Home/Lab?number=1");
            }
            ModelState.AddModelError(string.Empty, "Login error");
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Register(string returnUrl)
        {
            var viewModel = new RegisterViewModel
            {
                ReturnUrl = returnUrl
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var user = new AppUser
            {
                UserName = viewModel.UserName,
                PhoneNumber = viewModel.PhoneNumber,
                Email = viewModel.Email,
                FullName = viewModel.FullName
            };
            var result = await _userManager.CreateAsync(user, viewModel.Password);
            if (result.Succeeded)
            {
                var claims = new List<Claim>
                {
                    new Claim("fullname", user?.FullName)
                };
                await _signInManager.SignInWithClaimsAsync(user, false, claims);
                return Redirect("/Home/Lab?number=1");
            }
            ModelState.AddModelError(string.Empty, "Error occurred");
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            await _signInManager.SignOutAsync();
            var logoutRequest = await _interactionService.GetLogoutContextAsync(logoutId);
            return Redirect(logoutRequest.PostLogoutRedirectUri);
        }
    }
}

Lab5/Lab5/Controllers/HomeController.cs
using Lab5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IdentityModel;
using Lab5.Labs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Lab5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult Lab(int number)
        {
            ViewData["Lab"] = number;
            ILab lab;
            switch (number)
            {
                case 1:
                    lab = new Lab1();
                    break;
                case 2:
                    lab = new Lab2();
                    break;
                case 3:
                    lab = new Lab3();
                    break;
                default:
                    return Error();
            }
            ViewData["description"] = lab.Description;
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Lab(int number, string input)
        {
            ViewData["Lab"] = number;
            ILab lab;
            switch (number)
            {
                case 1:
                    lab = new Lab1();
                    break;
                case 2:
                    lab = new Lab2();
                    break;
                case 3:
                    lab = new Lab3();
                    break;
                default:
                    return Error();
            }
            ViewData["description"] = lab.Description;
            ViewData["output"] = lab.Execute(input);
            return View();
        }
        [Authorize]
        public IActionResult UserPage()
        {
            ViewData["username"] = User.Claims.FirstOrDefault(obj => obj.Type.Equals(JwtClaimTypes.Name))?.Value;
            ViewData["fullname"] = User.Claims.FirstOrDefault(obj => obj.Type.Equals("fullname"))?.Value;
            ViewData["email"] = User.Claims.FirstOrDefault(obj => obj.Type.Equals(JwtClaimTypes.Email))?.Value;
            ViewData["phone"] = User.Claims.FirstOrDefault(obj => obj.Type.Equals(JwtClaimTypes.PhoneNumber))?.Value;
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab5/Lab5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Lab 5 Iaresko Vlad</p>
</div>

Lab5/Lab5/Views/Home/Lab.cshtml
@{
    ViewData["Title"] = "Lab" + ViewData["Lab"];
}
<div class="text-center">
    <h1 class="display-4">Lab @ViewData["Lab"]</h1>
    <label>Description: @ViewData["description"]</label><br />
    <form method="post">
        <label>Input:</label><br />
        <textarea name="input"></textarea><br />
        <input type="submit" value="Send" /><br />
    </form>
    <label>Output:</label><br />
    <textarea name="output">@ViewData["output"]</textarea><br />
</div>

Lab5/Lab5/Views/Home/UserPage.cshtml
@{
    ViewData["Title"] = "User";
}
<div class="text-center">
    <h1 class="display-4">User Page</h1>
    <p>UserName: @ViewData["username"]</p>
    <p>Email: @ViewData["email"]</p>
    <p>Phone Number: @ViewData["phone"]</p>
    <p>Full Name: @ViewData["fullname"]</p>
</div>

Lab5/Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.Name != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="UserPage">User Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Lab" asp-route-number="1">Lab 1</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Lab" asp-route-number="2">Lab 2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Lab" asp-route-number="3">Lab 3</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>   
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lab5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>